name: global_chat
description: "A global chat made with flutter and firebase"

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # just some icons
  cupertino_icons: ^1.0.6
  # BLoC design pattern
  flutter_bloc: ^8.1.3
  # firebase database connection
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  # firebase auth
  firebase_auth: ^4.15.3
  # google sign in
  google_sign_in: ^6.2.1
  # dependency injection
  get_it: ^7.6.4
  # data persistence
  shared_preferences: ^2.2.2
  # external links
  url_launcher: ^6.2.2
  # environment variables
  flutter_dotenv: ^5.1.0
  # localization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^3.0.1

flutter:

  assets:
    - .env
    - assets/icons/
    - assets/images/
  uses-material-design: true
